### ISSUE TITLE
Run without ngrok?

### ISSUE THREAD

**Issue by mensa84** [lzilioli/nokia-sleep-homebridge#1]
Hello,

is it possible to run that tool without ngrok?
I mean it should also work with homebridge-http-webhooks and port forwarding, or not? So why is ngrok needed? Only for installations where port forwardings are not allowed / possible?

**Comment by lzilioli** [comment]
@mensa84 for my purposes at the time, I needed ngrok since nokia sleep only allowed me to send requests via ifttatt, where local urls are not supported.

Removing ngrok is possible, but would require a bit of thought. I am getting ready to archive this repository, because I have actually stopped using this recently in favor of PushCut's automation server feature. PushCut has saved me a ton of time and eliminated the need for me to create little bridge modules like this, since I can do it all with an iOS device now. https://www.pushcut.io
